# -*- coding: utf-8 -*-
"""02_sales_forecasting_customer_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lphloqi1zFXhuaOCiRPjQ864qY1eGdre
"""

# ==============================
# IMPORT LIBRARIES
# ==============================
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# ==============================
# LOAD DATA
# ==============================
df = pd.read_csv("superstore_cleaned.csv", encoding="latin1")

# Clean columns
df.columns = df.columns.str.lower().str.replace(" ", "_")

# Convert dates
df['order_date'] = pd.to_datetime(df['order_date'])

# ==============================
# FEATURE ENGINEERING (IMPORTANT)
# ==============================

# Extract time features
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_dayofweek'] = df['order_date'].dt.dayofweek

# Profit ratio (important business feature)
df['profit_ratio'] = df['profit'] / (df['sales'] + 1)

# ==============================
# CUSTOMER SEGMENTATION
# ==============================
customer_data = df.groupby('customer_id').agg({
    'sales': 'sum',
    'quantity': 'sum',
    'order_id': 'count'
}).reset_index()

scaler = StandardScaler()
scaled_data = scaler.fit_transform(
    customer_data[['sales', 'quantity', 'order_id']]
)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
customer_data['cluster'] = kmeans.fit_predict(scaled_data)

# Plot customer segments
plt.figure(figsize=(8,6))
plt.scatter(customer_data['sales'],
            customer_data['quantity'],
            c=customer_data['cluster'])
plt.xlabel("Total Sales")
plt.ylabel("Quantity")
plt.title("Customer Segmentation")
plt.colorbar(label="Cluster")
plt.show()

# ==============================
# PREPARE DATA FOR PREDICTION
# ==============================

# Select IMPORTANT features
features = df[[
    'quantity',
    'discount',
    'profit',
    'profit_ratio',
    'order_month',
    'order_dayofweek',
    'segment',
    'category',
    'ship_mode',
    'region'
]]

target = df['sales']

# One-Hot Encoding (BEST practice)
features = pd.get_dummies(features, drop_first=True)

# ==============================
# TRAIN TEST SPLIT
# ==============================
X_train, X_test, y_train, y_test = train_test_split(
    features,
    target,
    test_size=0.2,
    random_state=42
)

# ==============================
# RANDOM FOREST (OPTIMIZED)
# ==============================
rf_model = RandomForestRegressor(
    n_estimators=400,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

# ==============================
# PREDICTIONS
# ==============================
predictions = rf_model.predict(X_test)

# ==============================
# EVALUATION (ERROR ANALYSIS)
# ==============================
mse = mean_squared_error(y_test, predictions)
rmse = mse ** 0.5
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("\nModel Performance")
print("----------------------")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"MAE  : {mae:.2f}")
print(f"R2   : {r2:.3f}")

# ==============================
# ACTUAL VS PREDICTED PLOT
# ==============================
plt.figure(figsize=(8,6))
plt.plot(y_test.values[:200], label="Actual")
plt.plot(predictions[:200], linestyle='--', label="Predicted")
plt.title("Actual vs Predicted Sales")
plt.xlabel("Sample Index")
plt.ylabel("Sales")
plt.legend()
plt.show()

# ==============================
# RESIDUAL ERROR PLOT
# ==============================
residuals = y_test - predictions

plt.figure(figsize=(8,6))
plt.scatter(predictions, residuals, alpha=0.5)
plt.axhline(0)
plt.xlabel("Predicted Sales")
plt.ylabel("Residual Error")
plt.title("Residual Analysis")
plt.show()

"""This notebook performs a series of data analysis and machine learning tasks on a Superstore sales dataset. It covers data loading, cleaning, customer segmentation using K-Means, various data visualizations, and sales forecasting using a Random Forest Regressor.

### 1. Library Imports and Data Loading

The code begins by importing necessary libraries for data manipulation (`pandas`), plotting (`matplotlib`), and machine learning (`sklearn` for scaling, clustering, and regression). It then loads the 'Sample - Superstore.csv' dataset into a pandas DataFrame. The `Order Date` column is converted to datetime objects, and column names are cleaned for easier access.
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

# Convert the 'Order Date' column to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Clean column names
df.columns = df.columns.str.lower().str.replace(" ", "_")

"""### 2. Customer Segmentation (K-Means Clustering)

This section aggregates sales data by `customer_id` to create a `customer_data` DataFrame, summarizing total `sales`, `quantity`, and `order_id` count for each customer. It then uses `StandardScaler` to normalize these features and applies K-Means clustering with 3 clusters to segment customers based on their purchasing behavior. A scatter plot visualizes these customer segments.
"""

# Create Customer Data
customer_data = df.groupby('customer_id').agg({
    'sales': 'sum',
    'quantity': 'sum',
    'order_id': 'count'
}).reset_index()

# KMeans clustering (Customer Segmentation)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(customer_data[['sales', 'quantity', 'order_id']])

kmeans = KMeans(n_clusters=3, random_state=42)
customer_data['cluster'] = kmeans.fit_predict(scaled_data)

# Create scatter plot of customer segments
plt.figure(figsize=(8, 6))
plt.scatter(customer_data['sales'], customer_data['quantity'], c=customer_data['cluster'], cmap='viridis')
plt.xlabel('Total Sales')
plt.ylabel('Quantity')
plt.title('Customer Segments')
plt.colorbar(label='Cluster')
plt.show()

"""### 3. Additional Visualizations

The code then generates three additional plots to gain further insights into the data:
1.  **Sales Distribution**: A histogram showing the distribution of sales values.
2.  **Sales vs. Quantity**: A scatter plot illustrating the relationship between sales and quantity.
3.  **Customer Count per Segment**: A bar chart displaying the number of customers in each identified cluster.
"""

# Other Visualizations
# 1. Sales distribution (Histogram)
plt.figure(figsize=(8, 6))
plt.hist(df['sales'], bins=30, color='skyblue', edgecolor='black')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.title('Sales Distribution')
plt.show()

# 2. Sales vs. Quantity (Scatter plot)
plt.figure(figsize=(8, 6))
plt.scatter(df['sales'], df['quantity'], alpha=0.6, color='orange')
plt.xlabel('Total Sales')
plt.ylabel('Quantity')
plt.title('Sales vs Quantity')
plt.show()

# 3. Customer Count per Segment (Bar chart)
segment_counts = customer_data['cluster'].value_counts()
plt.figure(figsize=(8, 6))
segment_counts.plot(kind='bar', color='lightcoral')
plt.xlabel('Segment')
plt.ylabel('Number of Customers')
plt.title('Customer Count per Segment')
plt.xticks(rotation=0)
plt.show()

"""### 4. Sales Forecasting (Random Forest Regressor)

The final section focuses on sales forecasting. It prepares features (`quantity`, `discount`, `segment`) and the target variable (`sales`). The `segment` column is one-hot encoded (converted to numerical representation). The data is then split into training and testing sets, scaled using `StandardScaler`, and a `RandomForestRegressor` model is trained. Predictions are made on the test set, and a plot compares actual vs. predicted sales. Finally, the Mean Squared Error (MSE) is calculated and printed to evaluate the model's performance.
"""

# Sales Forecasting with Random Forest
# Prepare features and target for forecasting
features = df[['quantity', 'discount', 'segment']]  # Include segment encoding as a feature
features['segment'] = df['segment'].map({'Consumer': 0, 'Corporate': 1, 'Home Office': 2})  # Encoding 'Segment'
target = df['sales']

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

# Scaling the data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the Random Forest model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, y_train)

# Predictions
predictions = rf_model.predict(X_test_scaled)

# Plot actual vs predicted sales
plt.figure(figsize=(8, 6))
plt.plot(y_test.values, label='Actual Sales', color='green')
plt.plot(predictions, label='Predicted Sales', color='red', linestyle='--')
plt.title('Sales Forecasting - Actual vs Predicted')
plt.xlabel('Test Data Index')
plt.ylabel('Sales')
plt.legend()
plt.show()

# Calculate and print performance metrics
mse = mean_squared_error(y_test, predictions)
print(f"Mean Squared Error: {mse:.2f}")

!pip install fpdf